version: "3.8"
services:
  app:
    build: ./.docker/nginx
    container_name: minimalist-app
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "80:80"
    restart: always
    depends_on:
      - db
      - php

  php:
    # default hostname is php (service name)
    build: ./.docker/php
    container_name: minimalist-php
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      PHP_IDE_CONFIG: "serverName=MinimaList"

  db:
    build: ./.docker/db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/db/data:/var/lib/mysql

  adminer:
    build: ./.docker/adminer
    environment:
      - ADMINER_DEFAULT_SERVER=${DB_HOST}
      - ADMINER_DEFAULT_USER=${DB_USER}
      - ADMINER_DEFAULT_PASSWORD=${DB_PASSWORD}
      - ADMINER_DEFAULT_PORT=${DB_PORT}
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /sessions
    depends_on:
      - db
